### ISSUE TITLE
RFE: Buildah buildstep plugin

### ISSUE THREAD

**Issue by LorbusChris** [containerbuildsystem/atomic-reactor#1147]
Hi,

I would like the ability to use `buildah bud` or `podman build` for building images instead of Docker.

A recent addition has been the imagebuilder buildstep plugin, which is great for reference, but unfortunately imagebuilder also relies on Docker for doing the build and there are [no plans to add a buildah backend to it.](https://github.com/openshift/imagebuilder/issues/33)

As of now, there are no python bindings for the `podman build` command either, so they probably need to be added to https://github.com/containers/libpod/tree/master/contrib/python/ first to facilitate this.

**Comment by LorbusChris** [comment]
There is [imagebuildah](https://github.com/containers/buildah/tree/master/imagebuildah) in the buildah repo, which pulls in imagebuilder. Maybe with the right configuration that can be used with the existing imagebuilder buildstep plugin?

**Comment by twaugh** [comment]
The CLI is 'buildah' (imagebuildah is a package which makes up part of that command).

We don't have plans to work on this yet, so please feel free to see if you can get it working. :-)

**Comment by lcarva** [comment]
We added a buildah build plugin: https://github.com/containerbuildsystem/atomic-reactor/blob/master/atomic_reactor/plugins/build_buildah.py

But buildah doesn't work well on OPC3, and OSBS as a whole cannot run on OCP4...

We are currently in the process of a big change in OSBS to leverage Tekton instead of BuildConfigs. Closing this issue as it's part of this larger effort.
